Fix failing goodbye step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -35,8 +35,8 @@ jobs:
   echo-goodbye:
       runs-on: ubuntu-latest
       steps:
-        - name: Failed step
-          run: |
-            exit 1
+        # - name: Failed step
+        #   run: |
+        #     exit 1
         - name: Say goodbye
           run: echo "Goodbye!"
